### ISSUE TITLE
Association Table Adds "gmsh:physical" which breaks import function

### ISSUE THREAD

**Issue by JET-Sci** [floiseau/msh2xdmf#12]
For an unknown reason msh2xdmf.py ran into an issue recently where it included "gmsh:physical = 1" in the association table. This ended up breaking the msh2xdmf.py import function. I was able to fix this using a simple if statement to see if the code was going to add "gmsh:physical" as a label. This changes the code as follows:

`if label != "gmsh:bounding_entities":
            value = msh.cell_data["gmsh:physical"][index][0]
            # Store the association table in a dictionnary
            association_table[label] = value
            # Display the association
            if verbose:
            	print(formatter.format(label, value))`

My version of msh2xdmf.py is available at: https://github.com/JET-Sci/msh2xdmf.git

**Comment by floiseau** [comment]
Thanks for reporting and correcting the issue! I included your fix in the code.
