### ISSUE TITLE
meshio

### ISSUE THREAD

**Issue by nschloe** [floiseau/msh2xdmf#3]
Just a heads-up that [meshio](https://github.com/nschloe/meshio/) exists for this purpose already.

**Comment by floiseau** [comment]
The idea is to facilitate the export of the GMSH physical groups in order to ease the setup of Fenics problem as it can not easily be done directly with meshio. Maybe this script could be included in meshio.

**Comment by nschloe** [comment]
Why can't it be done with meshio? Is this a bug perhaps?

**Comment by floiseau** [comment]
The problem does not come from meshio but from fenics: the current stable version can not read mesh with mixed element. As of now, the best solution is to export the boundary regions in a separate XMDF file.

**Comment by nschloe** [comment]
Ah, the mixed regions. Alright, yes.
