### ISSUE TITLE
Handle case where there is only one array in `msh.cells`

### ISSUE THREAD

**Issue by ConradJohnston** [floiseau/msh2xdmf#5]
Hi @floiseau , many thanks for the nice and useful tool.

I encountered an issue when trying to covert a .msh file with fewer than 2 physical groups defined.
The code throws an exception on this line:
https://github.com/floiseau/msh2xdmf/blob/5262bdb69bcfbf3e67b231f493a46b60ac92baa9/msh2xdmf.py#L45-L47

It complains:
`ValueError: need at least one array to concatenate` 
in the case where there is only one array in `msh.cells`.

If this is a valid use case then I think there just needs to be a small tweak to handle this gracefully.

**Comment by floiseau** [comment]
Thanks for reporting this issue. I believe that the issue is fixed. In fact, this error appears when there is no physical group defining boundaries or domains.

**Comment by ConradJohnston** [comment]
Looks great, thank you and can confirm it works when one of these groups is missing. 

I do notice that if no physical groups are defined at all, one gets an error like:
```
Traceback (most recent call last):
  File "/Users/cjohnson/Code/msh2xdmf/msh2xdmf.py", line 219, in <module>
    msh2xdmf(args.msh_file, args.dimension, directory=current_directory)
  File "/Users/cjohnson/Code/msh2xdmf/msh2xdmf.py", line 26, in msh2xdmf
    export_domain(msh, dim, directory)
  File "/Users/cjohnson/Code/msh2xdmf/msh2xdmf.py", line 61, in export_domain
    [
  File "/Users/cjohnson/Code/msh2xdmf/msh2xdmf.py", line 62, in <listcomp>
    msh.cell_data["gmsh:physical"][i]
KeyError: 'gmsh:physical'
```

**Comment by floiseau** [comment]
In fact, if there is no physical groups, the script should output empty files. I added an exception to let the user know that the domain must be set in a physical group.
